name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build Docker image
      run: |
        set -x
        docker build -t public.ecr.aws/r2o3x0u0/my-flask-app-repo:latest .
      
        docker push public.ecr.aws/r2o3x0u0/my-flask-app-repo:latest

    - name: Update ECS Service
      run: |
        TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition my-task-family --region us-east-1 | jq -r '.taskDefinition.taskDefinitionArn')

        NEW_TASK_DEFINITION_ARN=$(aws ecs register-task-definition \
          --family my-task-family \
          --network-mode awsvpc \
          --requires-compatibilities FARGATE \
          --cpu "256" \
          --memory "512" \
          --container-definitions '[{
            "name": "flask-container",
            "image": "public.ecr.aws/r2o3x0u0/my-flask-app-repo:latest",
            "essential": true,
            "memory": 512,
            "cpu": 256,
            "portMappings": [{
              "containerPort": 5000,
              "hostPort": 5000
            }],
            "healthCheck": {
              "command": ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"],
              "interval": 30,
              "retries": 3,
              "startPeriod": 0,
              "timeout": 5
            }
          }]' \
          --query 'taskDefinition.taskDefinitionArn' \
          --output text \
          --region us-east-1)

        aws ecs update-service --cluster my-ecs-cluster --service my-ecs-service --task-definition $NEW_TASK_DEFINITION_ARN --region us-east-1
