name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Register new Task Definition
      run: |
        NEW_TASK_DEFINITION_ARN=$(aws ecs register-task-definition \
          --family my-task-family \
          --network-mode awsvpc \
          --requires-compatibilities FARGATE \
          --cpu "256" \
          --memory "512" \
          --container-definitions '[{
            "name": "flask-container",
            "image": "${{ secrets.ECR_REPOSITORY }}:latest",
            "essential": true,
            "memory": 512,
            "cpu": 256,
            "portMappings": [{
              "containerPort": 5000,
              "hostPort": 5000
            }],
            "healthCheck": {
              "command": ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"],
              "interval": 30,
              "retries": 3,
              "startPeriod": 0,
              "timeout": 5
            }
          }]' \
          --query 'taskDefinition.taskDefinitionArn' \
          --output text \
          --region us-east-1)
        
        echo "New Task Definition ARN: $NEW_TASK_DEFINITION_ARN"

    - name: Update ECS Service
      run: |
        aws ecs update-service --cluster my-ecs-cluster --service my-ecs-service --task-definition $NEW_TASK_DEFINITION_ARN --region us-east-1
